esphome:
  name: core1
  friendly_name: CORE1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pfPPbfDJpMdl++qhjLVKhDrsWKpa1CmSwYTnVxjAOSo="

ota:
  password: "8d85dcdd8280e47d472c0d8cc0be39c0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Core1 Fallback Hotspot"
    password: "c9TcTry6xyzf"

captive_portal:
    